// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmta_tx6hV9w8RTckN_enFDYk9BWtZh2I',
    appId: '1:338517101876:android:187d851ce4b675cc1ca961',
    messagingSenderId: '338517101876',
    projectId: 'travel-app-75d37',
    storageBucket: 'travel-app-75d37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL9AH5lXJRsG1ir3kPjqU-8acnIn4A73Y',
    appId: '1:338517101876:ios:9fbc61247589f2af1ca961',
    messagingSenderId: '338517101876',
    projectId: 'travel-app-75d37',
    storageBucket: 'travel-app-75d37.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_u-qMMumTriOvncFy1VuOx1_nJ2mhsDo',
    appId: '1:338517101876:web:9dd29bba609bb3fc1ca961',
    messagingSenderId: '338517101876',
    projectId: 'travel-app-75d37',
    authDomain: 'travel-app-75d37.firebaseapp.com',
    storageBucket: 'travel-app-75d37.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL9AH5lXJRsG1ir3kPjqU-8acnIn4A73Y',
    appId: '1:338517101876:ios:9fbc61247589f2af1ca961',
    messagingSenderId: '338517101876',
    projectId: 'travel-app-75d37',
    storageBucket: 'travel-app-75d37.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_u-qMMumTriOvncFy1VuOx1_nJ2mhsDo',
    appId: '1:338517101876:web:a8897d5301d613c21ca961',
    messagingSenderId: '338517101876',
    projectId: 'travel-app-75d37',
    authDomain: 'travel-app-75d37.firebaseapp.com',
    storageBucket: 'travel-app-75d37.appspot.com',
  );

}